export default [
    "np-icon-tubiao",
    "np-icon-huanfu",
    "np-icon-fuzhi",
    "np-icon-zip",
    "np-icon-bg-pdf",
    "np-icon-icon",
    "np-icon-excel",
    "np-icon-nested",
    "np-icon-link",
    "np-icon-dangqian",
    "np-icon-dangqianlouceng",
    "np-icon-baocun",
    "np-icon-qingli",
    "np-icon-search",
];
