export default [
    "404",
    "personcenter",
    "nav_close",
    "nav_open",
    "search",
    "yaoshi",
    "fullscreen",
    "exit-fullscreen",
    "message",
    "money",
    "shopcar",
    "usergroup",
    "book",
    "language",
];
