export default [
    {
        menuId: 1,
        title: "首页",
        path: "/dashboard",
        icon: "el-icon-s-home",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 1,
        children: [],
    },
    {
        menuId: 2,
        title: "图标",
        path: "/svg",
        icon: "np-icon-icon",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 2,
        children: [],
    },
    {
        menuId: 8,
        title: "权限测试页",
        path: "/permissions",
        icon: "el-icon-unlock",
        parentMenuId: null,
        keepAlive: false,
        status: 1,
        sort: 3,
        children: [],
    },
    {
        menuId: 3,
        title: "Clipboard",
        path: "/clipboard",
        icon: "np-icon-fuzhi",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 4,
        children: [],
    },
    {
        menuId: 4,
        title: "导出 File",
        path: "/exportFile",
        icon: "np-icon-file",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 5,
        children: [],
    },
    {
        menuId: 5,
        title: "组件",
        path: "/components",
        icon: "el-icon-menu",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 6,
        children: [
            {
                menuId: 51,
                title: "富文本编辑器",
                path: "/tinymce",
                icon: "",
                parentMenuId: 5,
                keepAlive: true,
                status: 1,
                sort: 1,
                children: [],
            },
            {
                menuId: 52,
                title: "JSON 编辑器",
                path: "/jsoneditor",
                icon: "",
                parentMenuId: 5,
                keepAlive: true,
                status: 1,
                sort: 2,
                children: [],
            },
            {
                menuId: 53,
                title: "图表",
                path: "/charts",
                icon: "",
                parentMenuId: 5,
                keepAlive: true,
                status: 1,
                sort: 3,
                children: [],
            },
        ],
    },
    {
        menuId: 6,
        title: "错误页面",
        path: "/error",
        icon: "el-icon-warning-outline",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 7,
        children: [
            {
                menuId: 61,
                title: "404",
                path: "/notFound",
                icon: "",
                parentMenuId: 6,
                keepAlive: true,
                status: 1,
                sort: 1,
                children: [],
            },
            {
                menuId: 62,
                title: "401",
                path: "/notPermission",
                icon: "",
                parentMenuId: 6,
                keepAlive: true,
                status: 1,
                sort: 2,
                children: [],
            },
        ],
    },
    {
        menuId: 7,
        title: "设置",
        path: "/setting",
        icon: "el-icon-s-tools",
        parentMenuId: null,
        keepAlive: true,
        status: 1,
        sort: 8,
        children: [
            {
                menuId: 71,
                title: "系统设置",
                path: "/system",
                icon: "",
                parentMenuId: 7,
                keepAlive: true,
                status: 1,
                sort: 1,
                children: [],
            },
            {
                menuId: 72,
                title: "菜单管理",
                path: "/menu",
                icon: "",
                parentMenuId: 7,
                keepAlive: true,
                status: 1,
                sort: 2,
                children: [],
            },
            {
                menuId: 73,
                title: "用户管理",
                path: "/user",
                icon: "",
                parentMenuId: 7,
                keepAlive: true,
                status: 1,
                sort: 3,
                children: [],
            },
        ],
    },
];
